[package]
name = "rapidbyte-core"
version.workspace = true
edition.workspace = true

[dependencies]
rapidbyte-sdk = { path = "../rapidbyte-sdk" }
tokio = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
serde_yaml = { workspace = true }
arrow = { workspace = true }
anyhow = { workspace = true }
thiserror = { workspace = true }
tracing = { workspace = true }
rusqlite = { workspace = true }
chrono = { workspace = true }
regex = "1"
wasmedge-sdk = { version = "0.14", features = ["standalone"] }
wasmedge-sys = "0.19"
wasmedge-types = "0.6"
sha2 = "0.10"
jsonschema = "0.28"
lz4_flex = "0.11"
zstd = "0.13"

[dev-dependencies]
tempfile = "3"
